/**
 * Immutable Godot milestone limits.
 *
 * Provider input cannot raise these limits and user configuration cannot
 * disable them. Truncation is always explicit; every bound is enforced by
 * the adapter during discovery, probing, and scanning.
 */
export const GODOT_LIMITS = {
  /** Maximum discovery candidates retained after validation. */
  maxCandidates: 16,
  /** Maximum accepted Godot executable size (512 MiB). */
  maxExecutableBytes: 512 * 1024 * 1024,
  /** Bounded `--version` output capture (64 KiB). */
  maxVersionOutputBytes: 64 * 1024,
  /** Bounded `--help` output capture (2 MiB). */
  maxHelpOutputBytes: 2 * 1024 * 1024,
  /** Bounded extension API dump file size (128 MiB). */
  maxApiDumpBytes: 128 * 1024 * 1024,
  /** Bounded project.godot size (4 MiB). */
  maxProjectFileBytes: 4 * 1024 * 1024,
  /** Bounded editor plugin descriptor size (256 KiB). */
  maxPluginDescriptorBytes: 256 * 1024,
  /** Bounded GDExtension descriptor size (1 MiB). */
  maxGDExtensionDescriptorBytes: 1024 * 1024,
  /** Maximum project files scanned by language and content inventory. */
  maxProjectFilesScanned: 50_000,
  /** Maximum project directories visited during static traversal (root counts). */
  maxProjectDirectoriesVisited: 10_000,
  /** Maximum project directory depth during static traversal (root counts). */
  maxProjectScanDepth: 64,
  /** Maximum readdir entries examined (excluded and non-regular entries count). */
  maxProjectEntriesExamined: 200_000,
  /** Maximum files surfaced in a static scan result. */
  maxProjectFilesSurfaced: 20_000,
  /** Maximum editor plugin directories enumerated in addons/. */
  maxProjectPluginDirectories: 256,
  /** Maximum plugin.cfg + .gdextension descriptors parsed per inspection. */
  maxProjectDescriptorsParsed: 512,
  /** Maximum executable-content inventory output items (scripts + plugins + descriptors + autoloads). */
  maxProjectInventoryItems: 4096,
  /** Maximum total raw file bytes read during content inventory (128 MiB). */
  maxProjectTotalReadBytes: 128 * 1024 * 1024,
  /** Maximum source bytes inspected by content inventory (64 MiB). */
  maxSourceBytesInspected: 64 * 1024 * 1024,
  /** Maximum tool-script head bytes scanned for `@tool` markers. */
  maxToolScriptHeadBytes: 32 * 1024,
  /** Maximum enabled editor plugin entries declared in project.godot. */
  maxProjectPlugins: 256,
  /** Maximum autoload declarations retained per project. */
  maxProjectAutoloads: 256,
  /** Maximum input-action declarations retained per project. */
  maxProjectInputActions: 512,
  /** Maximum event types retained per input action. */
  maxInputActionEventTypes: 16,
  /** Maximum GDExtension library targets assessed per descriptor. */
  maxGDExtensionTargetsPerDescriptor: 512,
  /** Maximum UTF-8 byte length of a project-provided res:// path reference. */
  maxResReferencePathBytes: 1024,
  /** Maximum UTF-8 byte length of a descriptor field value. */
  maxProjectDescriptorValueBytes: 16 * 1024,
  /** Maximum configured installation entries. */
  maxConfiguredInstallations: 16,
  /** Maximum installation id length. */
  maxInstallationIdLength: 64,
  /** Version probe timeout. */
  versionProbeTimeoutMs: 10_000,
  /** Help probe timeout. */
  helpProbeTimeoutMs: 15_000,
  /** Extension API dump probe timeout. */
  apiDumpTimeoutMs: 120_000,
  /** Static project scan timeout (checked during traversal). */
  staticProjectScanTimeoutMs: 30_000,
  /** Recovery-probe risk refresh deadline (static inspection + hashing). */
  riskRefreshTimeoutMs: 30_000,
  /** Disposable project mirror preparation deadline. */
  mirrorPrepareTimeoutMs: 120_000,
  /** Recovery-mode editor startup probe deadline. */
  recoveryProbeTimeoutMs: 60_000,
  /** Bounded editor iteration count for `--quit-after`. */
  recoveryQuitAfterIterations: 120,
  /** Post-probe `.godot` inspection deadline. */
  postProbeInspectionTimeoutMs: 30_000,
  /** Probe-directory cleanup deadline. */
  cleanupTimeoutMs: 60_000,
  /** Maximum mirror source files copied. */
  maxMirrorFiles: 100_000,
  /** Maximum mirror total bytes (4 GiB). */
  maxMirrorBytes: 4 * 1024 * 1024 * 1024,
  /** Maximum single mirror file bytes (512 MiB). */
  maxMirrorSingleFileBytes: 512 * 1024 * 1024,
  /** Maximum mirror relative path length in UTF-8 bytes. */
  maxMirrorRelativePathBytes: 1024,
  /** Maximum mirror directory depth. */
  maxMirrorDepth: 64,
  /** Per-stream recovery probe output capture (1 MiB). */
  maxRecoveryStreamBytes: 1024 * 1024,
  /** Maximum normalized recovery diagnostics retained per severity. */
  maxRecoveryDiagnostics: 100,
  /** Maximum raw recovery diagnostic lines retained for display. */
  maxRawDiagnosticLines: 200,
  /** Maximum `.godot` generated files inspected after the probe. */
  maxGeneratedGodotFiles: 20_000,
  /** Maximum `.godot` generated bytes inspected after the probe. */
  maxGeneratedGodotBytes: 512 * 1024 * 1024,
  /** Maximum authored files covered by a workspace integrity baseline. */
  maxBaselineManifestFiles: 100_000,
  /** Maximum authored bytes covered by a workspace integrity baseline. */
  maxBaselineManifestBytes: 4 * 1024 * 1024 * 1024,
  /** Maximum simultaneously prepared recovery probes (bounded prepared state). */
  maxPreparedProbes: 8,
  /** Maximum aggregate serialized bytes of all prepared probe plans. */
  maxPreparedProbeStateBytes: 8 * 1024 * 1024,
  /** Maximum lifetime of a prepared probe before it expires. */
  preparedProbeTtlMs: 10 * 60 * 1000,

  // --- Version-matched Godot API knowledge ---
  /** Maximum accepted `--dump-extension-api-with-docs` output file (256 MiB). */
  maxApiDumpWithDocsBytes: 256 * 1024 * 1024,
  /** Maximum indexed API classes (native + built-in). */
  maxApiClasses: 20_000,
  /** Maximum indexed API symbols (classes, members, globals, utilities). */
  maxApiSymbols: 500_000,
  /** Maximum retained description length for one API symbol (256 KiB). */
  maxApiDescriptionBytes: 256 * 1024,
  /** Maximum search-result snippet length (2 KiB). */
  maxApiSummaryBytes: 2 * 1024,
  /** Maximum API search results returned to the provider or CLI. */
  maxApiSearchResults: 25,
  /** Maximum serialized API lookup result bytes (512 KiB). */
  maxApiLookupResultBytes: 512 * 1024,
  /** Knowledge profile schema version (immutable; mismatch rebuilds the cache). */
  knowledgeSchemaVersion: 1,
  /** With-docs API dump probe timeout (fixed Siralos probe). */
  apiDocsDumpTimeoutMs: 180_000,

  // --- GDScript check-only diagnostics ---
  /** Maximum checked GDScript file size (4 MiB). */
  maxGDScriptFileBytes: 4 * 1024 * 1024,
  /** Maximum scripts enumerated per project-wide check. */
  maxGDScriptFilesPerProject: 10_000,
  /** Maximum aggregate GDScript bytes per project-wide check. */
  maxGDScriptTotalBytes: 256 * 1024 * 1024,
  /** Maximum normalized diagnostics retained for one script. */
  maxDiagnosticsPerScript: 500,
  /** Maximum normalized diagnostics retained for one check run. */
  maxDiagnosticsPerRun: 10_000,
  /** Maximum retained length of one normalized diagnostic message (8 KiB). */
  maxDiagnosticMessageBytes: 8 * 1024,
  /** Single check-only invocation timeout (30 seconds). */
  gdscriptCheckTimeoutMs: 30_000,
  /** Total budget for one project-wide diagnostic run (10 minutes). */
  projectDiagnosticsBudgetMs: 10 * 60 * 1000,
  /** Maximum raw output bytes captured per check stream. */
  maxCheckStreamBytes: 8 * 1024 * 1024,
  /** Maximum simultaneously prepared GDScript checks. */
  maxPreparedChecks: 8,
  /** Maximum aggregate serialized bytes of all prepared check plans. */
  maxPreparedCheckStateBytes: 8 * 1024 * 1024,
  /** Maximum lifetime of a prepared check before it expires. */
  preparedCheckTtlMs: 10 * 60 * 1000,

  // --- Bounded Godot GDScript LSP client ---
  /** Maximum incoming LSP message body (16 MiB). */
  lspMessageBodyBytes: 16 * 1024 * 1024,
  /** Maximum LSP header block (32 KiB). */
  lspHeaderBytes: 32 * 1024,
  /** Maximum concurrent pending JSON-RPC requests. */
  lspMaxPendingRequests: 128,
  /** Maximum simultaneously open LSP documents. */
  lspMaxOpenDocuments: 256,
  /** Maximum normalized diagnostics retained per document. */
  lspMaxDiagnosticsPerDocument: 2_000,
  /** Maximum completion items returned per query. */
  lspMaxCompletionItems: 500,
  /** Maximum retained hover content bytes (512 KiB). */
  lspMaxHoverBytes: 512 * 1024,
  /** Maximum definition locations returned per query. */
  lspMaxDefinitionLocations: 100,
  /** LSP session startup timeout (30 seconds). */
  lspStartupTimeoutMs: 30_000,
  /** LSP request timeout (15 seconds). */
  lspRequestTimeoutMs: 15_000,
  /** LSP session idle timeout (10 minutes). */
  lspIdleTimeoutMs: 10 * 60 * 1000,
  /** Maximum LSP session lifetime (30 minutes). */
  lspMaxSessionLifetimeMs: 30 * 60 * 1000,
  /** Bounded shutdown wait after LSP shutdown (5 seconds). */
  lspShutdownTimeoutMs: 5_000,
  /** LSP session policy version (binds every approval). */
  lspPolicyVersion: 1,
  /** Maximum simultaneously prepared LSP sessions. */
  maxPreparedLSPSessions: 4,
  /** Maximum aggregate serialized bytes of all prepared LSP session plans. */
  maxPreparedLSPSessionStateBytes: 8 * 1024 * 1024,
  /** Maximum lifetime of a prepared LSP session before it expires. */
  preparedLSPSessionTtlMs: 10 * 60 * 1000,
} as const;
