/**
 * Immutable Godot milestone limits.
 *
 * Provider input cannot raise these limits and user configuration cannot
 * disable them. Truncation is always explicit; every bound is enforced by
 * the adapter during discovery, probing, and scanning.
 */
export const GODOT_LIMITS = {
  /** Maximum discovery candidates retained after validation. */
  maxCandidates: 16,
  /** Maximum accepted Godot executable size (512 MiB). */
  maxExecutableBytes: 512 * 1024 * 1024,
  /** Bounded `--version` output capture (64 KiB). */
  maxVersionOutputBytes: 64 * 1024,
  /** Bounded `--help` output capture (2 MiB). */
  maxHelpOutputBytes: 2 * 1024 * 1024,
  /** Bounded extension API dump file size (128 MiB). */
  maxApiDumpBytes: 128 * 1024 * 1024,
  /** Bounded project.godot size (4 MiB). */
  maxProjectFileBytes: 4 * 1024 * 1024,
  /** Bounded editor plugin descriptor size (256 KiB). */
  maxPluginDescriptorBytes: 256 * 1024,
  /** Bounded GDExtension descriptor size (1 MiB). */
  maxGDExtensionDescriptorBytes: 1024 * 1024,
  /** Maximum project files scanned by language and content inventory. */
  maxProjectFilesScanned: 50_000,
  /** Maximum source bytes inspected by content inventory (64 MiB). */
  maxSourceBytesInspected: 64 * 1024 * 1024,
  /** Maximum tool-script head bytes scanned for `@tool` markers. */
  maxToolScriptHeadBytes: 32 * 1024,
  /** Maximum configured installation entries. */
  maxConfiguredInstallations: 16,
  /** Maximum installation id length. */
  maxInstallationIdLength: 64,
  /** Version probe timeout. */
  versionProbeTimeoutMs: 10_000,
  /** Help probe timeout. */
  helpProbeTimeoutMs: 15_000,
  /** Extension API dump probe timeout. */
  apiDumpTimeoutMs: 120_000,
  /** Static project scan timeout (checked during traversal). */
  staticProjectScanTimeoutMs: 30_000,
  /** Recovery-probe risk refresh deadline (static inspection + hashing). */
  riskRefreshTimeoutMs: 30_000,
  /** Disposable project mirror preparation deadline. */
  mirrorPrepareTimeoutMs: 120_000,
  /** Recovery-mode editor startup probe deadline. */
  recoveryProbeTimeoutMs: 60_000,
  /** Bounded editor iteration count for `--quit-after`. */
  recoveryQuitAfterIterations: 120,
  /** Post-probe `.godot` inspection deadline. */
  postProbeInspectionTimeoutMs: 30_000,
  /** Probe-directory cleanup deadline. */
  cleanupTimeoutMs: 60_000,
  /** Maximum mirror source files copied. */
  maxMirrorFiles: 100_000,
  /** Maximum mirror total bytes (4 GiB). */
  maxMirrorBytes: 4 * 1024 * 1024 * 1024,
  /** Maximum single mirror file bytes (512 MiB). */
  maxMirrorSingleFileBytes: 512 * 1024 * 1024,
  /** Maximum mirror relative path length in UTF-8 bytes. */
  maxMirrorRelativePathBytes: 1024,
  /** Maximum mirror directory depth. */
  maxMirrorDepth: 64,
  /** Per-stream recovery probe output capture (1 MiB). */
  maxRecoveryStreamBytes: 1024 * 1024,
  /** Maximum normalized recovery diagnostics retained per severity. */
  maxRecoveryDiagnostics: 100,
  /** Maximum raw recovery diagnostic lines retained for display. */
  maxRawDiagnosticLines: 200,
  /** Maximum `.godot` generated files inspected after the probe. */
  maxGeneratedGodotFiles: 20_000,
  /** Maximum `.godot` generated bytes inspected after the probe. */
  maxGeneratedGodotBytes: 512 * 1024 * 1024,
  /** Maximum authored files covered by a workspace integrity baseline. */
  maxBaselineManifestFiles: 100_000,
  /** Maximum authored bytes covered by a workspace integrity baseline. */
  maxBaselineManifestBytes: 4 * 1024 * 1024 * 1024,
} as const;
