import { createServer } from "node:net";

/**
 * Siralos-owned dynamic loopback-only LSP port allocation.
 *
 * The port is generated by Siralos (never provider input), bound only to
 * `127.0.0.1`, chosen by the OS within the dynamic user-port range (the
 * OS assigns from its ephemeral range when asked for port 0), never
 * scanned across large ranges, race-safe (the OS allocation is the race
 * answer), and bounded in retries. The LSP connection is the only
 * loopback exception to the otherwise offline sandbox profile, and the
 * session reports the isolation scope truthfully.
 */

export interface AllocatedLSPPort {
  readonly host: "127.0.0.1";
  readonly port: number;
}

export interface LSPPortAllocator {
  /** Bind a loopback listener on port 0, record the OS-assigned port, close. */
  allocate(): Promise<AllocatedLSPPort>;
  /** Verify the port is no longer bound by Siralos (post-session check). */
  release(port: number): Promise<void>;
}

const MAX_ALLOCATION_ATTEMPTS = 5;

export function createLSPPortAllocator(): LSPPortAllocator {
  return {
    async allocate(): Promise<AllocatedLSPPort> {
      let lastError: unknown = null;
      for (let attempt = 0; attempt < MAX_ALLOCATION_ATTEMPTS; attempt += 1) {
        const server = createServer();
        try {
          await new Promise<void>((resolve, reject) => {
            server.once("error", reject);
            server.listen(0, "127.0.0.1", () => {
              server.removeListener("error", reject);
              resolve();
            });
          });
          const address = server.address();
          const port = typeof address === "object" && address !== null ? address.port : null;
          if (port === null || !Number.isInteger(port) || port <= 0 || port > 65535) {
            throw new Error("The OS did not return a valid ephemeral port.");
          }
          await new Promise<void>((resolve) => server.close(() => resolve()));
          return { host: "127.0.0.1", port };
        } catch (error: unknown) {
          lastError = error;
          try {
            server.close();
          } catch {
            // already closed
          }
        }
      }
      throw new Error(
        `The loopback LSP port could not be allocated after ${MAX_ALLOCATION_ATTEMPTS} attempts: ${describe(lastError)}`,
      );
    },
    async release(port: number): Promise<void> {
      const probe = createServer();
      try {
        await new Promise<void>((resolve, reject) => {
          probe.once("error", reject);
          probe.listen(port, "127.0.0.1", () => {
            probe.removeListener("error", reject);
            resolve();
          });
        });
        // Binding succeeded: the port is free again.
        await new Promise<void>((resolve) => probe.close(() => resolve()));
      } catch {
        // The port is still bound (or refused); the session host reports
        // cleanup status truthfully rather than claiming success.
        try {
          probe.close();
        } catch {
          // already closed
        }
        throw new Error(`The loopback LSP port ${port} is still in use after session cleanup.`);
      }
    },
  };
}

function describe(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
